"""Mapping of TSM (Ticaret Sicil Mudurlugu) city names to SicilMudurluguId values.

These IDs come from the dropdown on the TOBB ilan goruntuleme page.
Used to resolve a city name (from unvan sorgulama results) to the
numeric ID needed for the ilan goruntuleme POST form.
"""

from __future__ import annotations

TSM_TO_ID: dict[str, str] = {
    "ACIPAYAM": "1",
    "ADANA": "2",
    "ADIYAMAN": "3",
    "AFYONKARAHİSAR": "4",
    "AFŞİN": "5",
    "AKHİSAR": "6",
    "AKSARAY": "7",
    "AKYAZI": "8",
    "AKÇAKOCA": "9",
    "AKŞEHİR": "10",
    "ALACA": "11",
    "ALANYA": "12",
    "ALAPLI": "13",
    "ALAŞEHİR": "14",
    "ALİAĞA": "15",
    "AMASYA": "16",
    "ANAMUR": "17",
    "ANKARA": "18",
    "ANTALYA": "19",
    "ARDAHAN": "20",
    "ARDEŞEN": "21",
    "ARHAVİ": "22",
    "ARTVİN": "23",
    "AYDIN": "24",
    "AYVALIK": "25",
    "AĞRI": "26",
    "BABADAĞ": "27",
    "BABAESKİ": "28",
    "BAFRA": "29",
    "BALIKESİR": "30",
    "BANDIRMA": "31",
    "BARTIN": "32",
    "BATMAN": "33",
    "BAYBURT": "34",
    "BAYINDIR": "35",
    "BERGAMA": "36",
    "BEYPAZARI": "37",
    "BEYŞEHİR": "38",
    "BODRUM": "39",
    "BOLU": "40",
    "BOLVADİN": "41",
    "BOR": "42",
    "BORÇKA": "43",
    "BOYABAT": "44",
    "BOZÜYÜK": "45",
    "BOĞAZLIYAN": "46",
    "BUCAK": "47",
    "BULANCAK": "48",
    "BULDAN": "49",
    "BURDUR": "50",
    "BURHANİYE": "51",
    "BURSA": "52",
    "BÜNYAN": "53",
    "BİGA": "54",
    "BİLECİK": "55",
    "BİNGÖL": "56",
    "BİRECİK": "57",
    "BİTLİS": "58",
    "CEYHAN": "59",
    "CİZRE": "60",
    "DEMİRCİ": "61",
    "DENİZLİ": "62",
    "DEVELİ": "63",
    "DEVREK": "64",
    "DOĞANHİSAR": "65",
    "DOĞUBAYAZIT": "66",
    "DÖRTYOL": "67",
    "DÜZCE": "68",
    "DİDİM": "69",
    "DİNAR": "70",
    "DİYARBAKIR": "71",
    "EDREMİT": "72",
    "EDİRNE": "73",
    "ELAZIĞ": "74",
    "ELBİSTAN": "75",
    "EMİRDAĞ": "76",
    "ERBAA": "77",
    "ERCİŞ": "78",
    "ERDEK": "79",
    "ERDEMLİ": "80",
    "ERZURUM": "81",
    "ERZİN": "82",
    "ERZİNCAN": "83",
    "ESKİŞEHİR": "84",
    "FATSA": "85",
    "FETHİYE": "86",
    "GAZİANTEP": "87",
    "GEBZE": "88",
    "GEDİZ": "89",
    "GELİBOLU": "90",
    "GEMLİK": "91",
    "GEREDE": "92",
    "GÖNEN": "93",
    "GÖRDES": "94",
    "GÜMÜŞHACIKÖY": "95",
    "GÜMÜŞHANE": "96",
    "GİRESUN": "97",
    "HAKKARİ": "98",
    "HATAY": "99",
    "HAVZA": "100",
    "HAYMANA": "101",
    "HAYRABOLU": "102",
    "HOPA": "103",
    "ILGIN": "104",
    "ISPARTA": "105",
    "IĞDIR": "106",
    "KAHRAMANMARAŞ": "107",
    "KADİRLİ": "108",
    "KAMAN": "109",
    "KARABÜK": "110",
    "KARACABEY": "111",
    "KARAHALLI": "113",
    "KARAMAN": "114",
    "KARAPINAR": "115",
    "KARS": "116",
    "KASTAMONU": "117",
    "KAYSERİ": "118",
    "KELKİT": "120",
    "KEŞAN": "121",
    "KIRIKHAN": "122",
    "KIRIKKALE": "123",
    "KIRKLARELİ": "124",
    "KIRŞEHİR": "125",
    "KIZILTEPE": "126",
    "KOCAELİ": "127",
    "KONYA EREĞLİ": "128",
    "KONYA": "129",
    "KOZAN": "130",
    "KUMLUCA": "131",
    "KUŞADASI": "132",
    "KÖRFEZ": "133",
    "KÜTAHYA": "134",
    "KİLİS": "135",
    "LÜLEBURGAZ": "136",
    "MALATYA": "137",
    "MALKARA": "138",
    "MANAVGAT": "139",
    "MANİSA": "140",
    "MARDİN": "141",
    "MARMARİS": "142",
    "MENEMEN": "143",
    "MERSİN": "144",
    "MERZİFON": "145",
    "MUCUR": "146",
    "MUSTAFAKEMALPAŞA": "147",
    "MUT": "148",
    "MUĞLA": "149",
    "MUŞ": "150",
    "MİLAS": "151",
    "NAZİLLİ": "152",
    "NEVŞEHİR": "153",
    "NUSAYBİN": "154",
    "NİKSAR": "155",
    "NİZİP": "156",
    "NİĞDE": "157",
    "OLTU": "158",
    "ORDU": "159",
    "ORHANGAZİ": "160",
    "OSMANİYE": "161",
    "PASİNLER": "162",
    "PAZAR": "163",
    "POLATLI": "164",
    "REYHANLI": "165",
    "RİZE": "167",
    "SAFRANBOLU": "168",
    "SAKARYA": "169",
    "SALİHLİ": "170",
    "SAMSUN": "171",
    "SANDIKLI": "172",
    "SARAYKÖY": "173",
    "SELÇUK": "174",
    "SEYDİŞEHİR": "175",
    "SOMA": "176",
    "SULUOVA": "177",
    "SUNGURLU": "178",
    "SUSURLUK": "179",
    "SÖKE": "180",
    "SİLİFKE": "181",
    "SİMAV": "182",
    "SİNOP": "183",
    "SİVAS": "184",
    "SİVEREK": "185",
    "SİİRT": "186",
    "TARSUS": "187",
    "TATVAN": "188",
    "TAVAS": "189",
    "TAVŞANLI": "190",
    "TAŞKÖPRÜ": "191",
    "TEKİRDAĞ": "192",
    "TERME": "193",
    "TOKAT": "194",
    "TORBALI": "195",
    "TOSYA": "196",
    "TRABZON": "197",
    "TUNCELİ": "198",
    "TURGUTLU": "199",
    "TURHAL": "200",
    "TİRE": "201",
    "UZUNKÖPRÜ": "202",
    "UŞAK": "203",
    "VAN": "204",
    "VEZİRKÖPRÜ": "205",
    "YAHYALI": "206",
    "YALOVA": "207",
    "YALVAÇ": "208",
    "YENİŞEHİR": "209",
    "YERKÖY": "210",
    "YOZGAT": "211",
    "YÜKSEKOVA": "212",
    "ZONGULDAK": "213",
    "ZİLE": "214",
    "ÇANAKKALE": "215",
    "ÇANKIRI": "216",
    "ÇARŞAMBA": "217",
    "ÇAY": "218",
    "ÇAYCUMA": "219",
    "ÇAYELİ": "220",
    "ÇERKEZKÖY": "221",
    "ÇORLU": "222",
    "ÇORUM": "223",
    "ÇUMRA": "224",
    "ÖDEMİŞ": "225",
    "ÜNYE": "226",
    "ÜRGÜP": "227",
    "İNEBOLU": "228",
    "İNEGÖL": "229",
    "İSKENDERUN": "230",
    "İSLAHİYE": "231",
    "İSTANBUL": "232",
    "İZMİR": "233",
    "İZNİK": "234",
    "ŞANLIURFA": "235",
    "ŞEREFLİKOÇHİSAR": "236",
    "ŞIRNAK": "237",
    "SORGUN": "241",
    "OF": "242",
    "ŞEFAATLİ": "243",
    "KARADENİZ EREĞLİ": "246",
}


def _normalize_turkish(text: str) -> str:
    """Normalize Turkish characters for case-insensitive comparison.

    Handles Turkish-specific letters: İ/i and I/ı mapping.
    Converts to uppercase and normalizes Turkish dotted/dotless I variants
    to their ASCII equivalents for reliable lookup.
    """
    result = text.upper()
    # Turkish İ (U+0130) -> I
    result = result.replace("\u0130", "I")
    # Turkish ı (U+0131) uppercase is I, but just in case
    result = result.replace("\u0131", "I")
    return result


# Build a normalized lookup (Turkish-aware uppercase keys)
_NORMALIZED_LOOKUP: dict[str, str] = {_normalize_turkish(k): v for k, v in TSM_TO_ID.items()}


def resolve_tsm_id(tsm_name: str) -> str | None:
    """Resolve a TSM city name to its SicilMudurluguId, case-insensitive.

    Handles Turkish character case folding (İ/i, I/ı).
    Returns None if the city name is not found in the mapping.
    """
    if not tsm_name:
        return None
    return _NORMALIZED_LOOKUP.get(_normalize_turkish(tsm_name.strip()))
